//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidationDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string ThemeColor { get; set; }
        public bool IsFullDay { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Recurrence { get; set; }
        public string RecurrencePattern { get; set; }
        public string Location { get; set; }
        public string RecurrenceCount { get; set; }
        public string RecurrenceInterval { get; set; }
    }
}
